name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@689fb39b34b9aa95ebc5f8f119343ddd51542402
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

